### ISSUE TITLE
Добавить изменение приоритета процессов

### ISSUE THREAD

**Issue by neakyKazuto** [Htomsik/LTaskManager#27]

**Comment by Htomsik** [comment]
## Что требуется сделать
- Изменение приоритета процесса путем смены значения в ячейке таблицы процессов 


## Как нужно делать
**Neaky:**

1. В таблице заменить DataGridTextColumn на кастомную ячейку (DataGridTemplateColumn) которая будет содержать в себе комбобокс
  1.1. К свойству SelectedItem прибиндить значение приоритета отвечающее за приоритет
  1.2. К свойству Items прибиндить значение приоритета через конвертер EnumToCollectionConverter (конвертер будет генерировать все значения возможноные для этого енама и выводить их списком)
      
2. Доработать TaskProcess 
  2.1. Добавить наследование от ReactiveObject
  2.2. Добавить бэкграунд к кстомнуму свойству отвечающему за приоритет
  2.3. Сделать функцию которая будет возвращать bool значение в зависимости от результата и принимать аргумент с типом ProcessPriorityClass внутри, функции менять у _windowsProcess приоритет в зависимости от переданного значения. Если удалось произвести замену: Подгрузить новое значение в бэкграунд свойства PriorityClassCore 
  2.4 Добавить обращение к созданному методу в set свойства приоритета.
   > - Если метод вернул true то записывать в бэкграунд свойство переданное значение (value)
   > - В конце set обязательно this.RaisePropertyChanged(nameof(наименование свойства)), так требуется чтобы уведомить view о том что значение изменилось.

**Htmosik:**
- Добавить конвертер enumа  в коллекцию чтобы ее можно было прибиндить в качестве источника значений к combobox

> - Как работает свойство [ССЫЛКА](https://metanit.com/sharp/tutorial/3.4.php)
> - Пример Свойства с бэкграудом в Models/AppSettings свойство ProcessUpdateTimeOut
> - Как работает DataGridTextColumn можно посмотреть: [ССЫЛКА](https://docs.avaloniaui.net/docs/controls/datagrid/datagridcolumns#datagridtemplatecolumn)
> - Примеры как делается combobox  [ССЫЛКА1](https://play.avaloniaui.net/) [ССЫЛКА2](https://docs.avaloniaui.net/docs/controls/combobox) (Вместо прописывания ComboboxItem они будут генерироваться из enuma)
> - Что такое дататемплейт и как работает: [ССЫЛКА](https://docs.avaloniaui.net/docs/templates/data-templates)
> - Что такое конвертер: [ССЫЛКА](https://docs.avaloniaui.net/docs/data-binding/converting-binding-values)
> - Для Htomsik. Пример работы конвертера енамов в коллекцию [ССЫЛКА](https://stackoverflow.com/questions/6145888/how-to-bind-an-enum-to-a-combobox-control-in-wpf)

**Comment by Htomsik** [comment]
Свою часть сделал
