### ISSUE TITLE
Реализация фильтров для колонок с процессами

### ISSUE THREAD

**Issue by neakyKazuto** [Htomsik/LTaskManager#8]
### Обязательно к выполнению:
1. Реализовать фильтр по принципу принадлежности процессов к процессам операционной системы. С помощью отдельной кнопки - галочки.
2. Реализовать фильтр по колонке product name, чтобы можно было фильтровать процессы по названию компании - разработчика процесса. Учесть то, что могут быть процессы без названия компании - определить их в отдельную группу "Без организации".

**Comment by Htomsik** [comment]
2 пункт будет реализован в #20 
Первый пункт реализуешь сам

**Comment by Htomsik** [comment]
Также починить поиск по имени
> Реализовать метод ToString в TaskProcess
> [ССЫЛКА](https://learn.microsoft.com/ru-ru/dotnet/api/system.object.tostring?view=net-7.0)

**Comment by Htomsik** [comment]
Оказалось что стандартный диспетчер задач определяет системные процессы тупо из жестко закодированного списка.
Реализуем также, список будет храниться пока что в листе.
Затем придумаем как его перенести в json файл
